### ISSUE TITLE
Missing action buttons

### ISSUE THREAD

**Issue by hirnworx** [confirado/apto-one-template#9]
In domain configration and some other menues, edit and all action buttons are missing. 
Through console i see they are commented out by <!--
<img width="2311" alt="Bildschirm­foto 2023-09-21 um 19 09 04" src="https://github.com/confirado/apto-one-template/assets/74244303/80421c83-75e8-49d7-ba5b-ed2cc30e9d4f">

**Comment by ronnybaumann** [comment]
@hirnworx some action buttons are disabled by default by the firewall.  If you log in with the superadmin user there are no restrictions. The superadmin user can adjust these restrictions via the menu item "Security->Firewall".
